# retrieved from https://catalogue.dataspace.copernicus.eu/odata/v1/Attributes(SENTINEL-3)

SENTINEL3 = {
    "productType": "String",
    "landCover": "Double",
    "cloudCover": "Double",
    "timeliness": "String",
    "brightCover": "Double",
    "coordinates": "String",
    "cycleNumber": "Integer",
    "orbitNumber": "Integer",
    "coastalCover": "Double",
    "processorName": "String",
    "closedSeaCover": "Integer",
    "openOceanCover": "Integer",
    "orbitDirection": "String",
    "processingDate": "DateTimeOffset",
    "snowOrIceCover": "Double",
    "lastOrbitNumber": "Integer",
    "operationalMode": "String",
    "processingLevel": "String",
    "processingCenter": "String",
    "processorVersion": "String",
    "salineWaterCover": "Double",
    "tidalRegionCover": "Double",
    "platformShortName": "String",
    "baselineCollection": "String",
    "lastOrbitDirection": "String",
    "processingBaseline": "String",
    "continentalIceCover": "Integer",
    "instrumentShortName": "String",
    "relativeOrbitNumber": "Integer",
    "freshInlandWaterCover": "Double",
    "lastRelativeOrbitNumber": "Integer",
    "platformSerialIdentifier": "String"
}
