# retrieved from https://catalogue.dataspace.copernicus.eu/odata/v1/Attributes(SENTINEL-1)

SENTINEL1 = {
    "productType": "String",
    "origin": "String",
    "datatakeID": "Integer",
    "timeliness": "String",
    "coordinates": "String",
    "cycleNumber": "Integer",
    "orbitNumber": "Integer",
    "sliceNumber": "Integer",
    "totalSlices": "Integer",
    "productClass": "String",
    "processorName": "String",
    "orbitDirection": "String",
    "processingDate": "DateTimeOffset",
    "operationalMode": "String",
    "processingLevel": "String",
    "swathIdentifier": "String",
    "processingCenter": "String",
    "processorVersion": "String",
    "segmentStartTime": "DateTimeOffset",
    "sliceProductFlag": "Boolean",
    "platformShortName": "String",
    "productGeneration": "DateTimeOffset",
    "processingBaseline": "String",
    "productComposition": "String",
    "instrumentShortName": "String",
    "relativeOrbitNumber": "Integer",
    "polarisationChannels": "String",
    "productConsolidation": "String",
    "platformSerialIdentifier": "String",
    "instrumentConfigurationID": "Integer",
    "startTimeFromAscendingNode": "Double",
    "completionTimeFromAscendingNode": "Double"
}
